allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@13.6.1'
  - miniflare@4.20260601.0
  - wrangler@4.97.0
onlyBuiltDependencies:
  - esbuild
  - sharp
